apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
      #ports:
      # No ports key above, as the worker app doesn't listen on any port.
      # Exposing a port means to make a process listen on that port.
