apiVersion: v1
kind: Service
metadata:
  name: redis  # Name of service is imp as others access the service by its name.
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP  # By default type of service is ClusterIP, even if we don't specify type.
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-pod
    app: demo-voting-app
