apiVersion: v1
kind: Pod
metadata:
  name:  nginx-pod
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox

# spec = {containers: [{name: "nginx", image: "nginx"},{name: "busybox", image: "busybox"}]}

# kubectl create -f pod.yml
# kubectl apply -f pod.yml
# Both create and apply commands of kubectl work in same way when creating objects.
# kubectl get pods
# kubectl describe pod <pod_name>
